### ISSUE TITLE
SSL HTTPS 

### ISSUE THREAD

**Issue by ghost** [sangnguyenplus/azquestion#13]
<img width="759" alt="screen shot 2016-01-14 at 3 43 09 pm" src="https://cloud.githubusercontent.com/assets/12554851/12318473/9ad1fc88-bad5-11e5-9452-c6cb01bee27a.png">
<img width="1280" alt="screen shot 2016-01-14 at 3 42 57 pm" src="https://cloud.githubusercontent.com/assets/12554851/12318474/9b30fec2-bad5-11e5-96be-16a73ca91a9b.png">

How to merge with the Server.js

**Comment by sangnguyenplus** [comment]
Hi @drgenesis ,
You dont need to change your source code. You just need to config ngnix using this script.

```
server {
    listen 80;
    server_name azquestion.com;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_post;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://128.199.130.111:3000;
        proxy_redirect off;

        # Socket.IO Support
        #proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
- Change azquestion.com to your domain and 128.199.130.111 to your server's IP.
