### ISSUE TITLE
Chuyển đổi tab sang space

### ISSUE THREAD

**Issue by namnv609** [sangnguyenplus/azquestion#4]
Bạn nên chuyển hết các tab sang spacebar đi. Lên Git nhìn rất là xấu.
Còn nữa, có rất nhiều nơi tab sai convention. Nếu rảnh, mình sẽ phụ sửa giúp bạn.

**Comment by TienTruongAnt** [comment]
1 tab cũng tương đương với 4 space mà, gõ phím tab nhanh hơn nhiều so với 4 phím space nên mình toàn dùng tab. 
Hồi viết cái này cũng không viết theo coding standard nào cả nên nó cũng nhiều chỗ nhìn không được đẹp :D

**Comment by namnv609** [comment]
Bạn hiểu sai ý tớ rồi. Translate tab sang 4 spacebar ấy bạn. Lên Git, nhìn 4 space ngắn hơn 1 tab!

**Comment by TienTruongAnt** [comment]
À, mình thấy rồi. Mà nhiều quá giờ sửa tốn nhiều thời gian lắm bạn ơi. Mình không có thời gian phát triển nữa nên public lên đây cho mọi người cùng phát triển, nếu bạn có thời gian phát triển thì hãy giúp mình nhé.

**Comment by namnv609** [comment]
OK bạn.
Mình cũng đang có ý tưởng, làm 1 web cho mọi người tập trung chia sẻ các git repo open source. Để mọi người tham gia phát triển. Hy vọng cộng đồng open source và Github của Việt Nam được phát triển như nước ngoài. Vào mấy repo open source của họ, nhìn số lượng pull request và issues mà thèm quá bạn ạ :confused:!

**Comment by sangnguyenplus** [comment]
Cảm ơn bạn trước nhé, hi vọng sớm nhận được sự đóng góp của bạn, cảm giác được chia sẻ và sử dụng source do người Việt chia sẻ chắc chắn sẽ tốt hơn nhiều so với dùng của tụi nước ngoài.
