### ISSUE TITLE
Can't create questions

### ISSUE THREAD

**Issue by drkeyongenesis** [sangnguyenplus/azquestion#9]
I downloaded the application and the create question feature isn't working at all. 

can someone help me?

**Comment by TienTruongAnt** [comment]
Hi @dr-teddygenesis, 
Could you please add some detail for your error, you can take a screenshot your error or show console detail.

**Comment by drkeyongenesis** [comment]
There isn't any error, it seem like it doesn't capture the question to MongoDb.
![error](https://cloud.githubusercontent.com/assets/14286179/9867217/bf00b186-5b9d-11e5-863b-3e34cb183d1c.PNG)

![error2](https://cloud.githubusercontent.com/assets/14286179/9867252/3bc44214-5b9e-11e5-9ecb-5b28f4146e9b.PNG)

**Comment by TienTruongAnt** [comment]
We need add index for title of post table, please use my demo database or add index for text column in questions table.
